### PR TITLE
Feature/wait for consul

### PR DESCRIPTION
**Pull request by skybert**
I've branched off my branch from `3.1.2-alpine` but cannot find that tag in the github interface (why?). I've therefore selected `3.1.2` as the base.

### CODE REVIEW

**Comment by iromli** [comment]
@skybert thanks for the pull request. We're using `3.1.2` branch for upcoming release. Can you revise your PR based on 3.1.2 branch?

**Comment by skybert** [comment]
Hi @iromli. I've rebased my branch unto `3.1.2`. A few more lines are contained in the PR diff, but `git annotate` on the file in question, `Dockerfile` is correct: 

```
0519c913 (iromli           2018-03-08 125) COPY scripts /opt/scripts                                                   
24bcacaa (Isman Firmansyah 2017-08-08 126) RUN chmod +x /opt/scripts/entrypoint.sh                                     
9187139f (Chris B          2018-01-24 127) ENTRYPOINT ["/bin/bash"]                                                    
24bcacaa (Isman Firmansyah 2017-08-08 128) CMD ["/opt/scripts/entrypoint.sh"]    
```

**Comment by iromli** [comment]
> Update: I merged upstream instead of rebasing onto it. The PR diff shouldn't differ, though. Only changes to lines from my commit should be in the PR diff. Odd.

Okay, let me check it locally first.

> FYI: I've rebased my other PRs in docker-oxauth, docker-openldap & docker-nginx against the upstream/3.1.2 branch.

Noted. I will check them as well.

**Comment by iromli** [comment]
@skybert got this error when running oxTrust:

```
oxtrust    | env: ‘bash’: No such file or directory
```

I think this is because we no longer install `bash` in oxTrust image.

**Comment by iromli** [comment]
My suggestion is to change `/bin/bash` to `/bin/sh` in your script.

**Comment by skybert** [comment]
Strange, I didn't get this error, then. Mhmm. 

In any case, I believe I need to rewrite portions of the script, then, as I'm using a couple of of BASH features.

**Comment by skybert** [comment]
Ok, I've changed the script to work on `dash` now (which AFAIK is closer to pure POSIX shell) and it makes the script work on `docker-oxauth` and `docker-oxtrust`. However, I see there are exceptions now in the python script which were not there before. As a consequence, the containers exit with `1`:

```
oxtrust_1  | Traceback (most recent call last):
oxtrust_1  |   File "/opt/scripts/entrypoint.py", line 81, in <module>
oxtrust_1  |     sync_ldap_pkcs12()
oxtrust_1  |   File "/opt/scripts/entrypoint.py", line 70, in sync_ldap_pkcs12
oxtrust_1  |     consul.kv.get("encoded_salt"))
oxtrust_1  |   File "/opt/scripts/entrypoint.py", line 64, in decrypt_text
oxtrust_1  |     decrypted_text += cipher.final()
oxtrust_1  |   File "/usr/lib/python2.7/site-packages/M2Crypto/EVP.py", line 128, in final
oxtrust_1  |     return m2.cipher_final(self.ctx)
oxtrust_1  | M2Crypto.EVP.EVPError: wrong final block length
docker_oxtrust_1 exited with code 1
```

**Comment by iromli** [comment]
@skybert can you check whether config has been populated in consul?

**Comment by skybert** [comment]
Yes, it looks good to my eyes:

```
$ curl -v  $(drip consul):8500/v1/kv/encoded_salt
*   Trying 172.19.0.2...
* TCP_NODELAY set
* Connected to 172.19.0.2 (172.19.0.2) port 8500 (#0)
> GET /v1/kv/encoded_salt HTTP/1.1
> Host: 172.19.0.2:8500
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Consul-Index: 7
< X-Consul-Knownleader: true
< X-Consul-Lastcontact: 0
< Date: Mon, 19 Mar 2018 17:31:16 GMT
< Content-Length: 195
< 
[
    {
        "LockIndex": 0,
        "Key": "encoded_salt",
        "Flags": 0,
        "Value": "VUdxQlZGSWVWTjZKUklnb3JIdkxFVWtZ",
        "CreateIndex": 7,
        "ModifyIndex": 7
    }
]
* Curl_http_done: called premature == 0
* Connection #0 to host 172.19.0.2 left intact
```

**Comment by iromli** [comment]
Let me check.

**Comment by skybert** [comment]
Perhaps I must use `docker-conf-init` from the `3.1.2` and not `:latest` from upstream/dockerhub?

**Comment by skybert** [comment]
Just wild guessing here: could it be that the changes in `entrypont.py` from 868a03b8a164b5da892052e881fcf24e29d6c76e doesn't match up with how the data are populated with `config-init`?

**Comment by iromli** [comment]
I'm pushing `3.1.2_dev` tag for all images into docker hub. Should be ready in few minutes.

**Comment by iromli** [comment]
@skybert you can build the docker image locally though; the code has been updated

**Comment by iromli** [comment]
@skybert `<image>:3.1.2_dev` pushed to docker hub. You may want to check docker-config-init README to see the changes (and perhaps purging old consul KV data).

**Comment by skybert** [comment]
Thanks @iromli , I've got everything working locally now after rebasing all my container forks on the `3.1.2` branches.

The change in LDAP port broke my setup, by the way, it took me a wee while to track down why oxauth and oxtrust couldn't initialise their LDAP connection pools: https://github.com/GluuFederation/docker-openldap/commit/b54ba2d28f8b78c7fda3bc5d11c961ffb18ab69f#diff-3254677a7917c6c01f55212f86c57fbfR65

**Comment by skybert** [comment]
I've created a new PR with correct commit log and diff: https://github.com/GluuFederation/docker-oxtrust/pull/2

**Pull request closed without merging**
